project_name: ezorm
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
release:
  github:
    owner: ezbuy
    name: ezorm
  extra_files:
    - glob: LICENSE


