USE [test]
GO
/****** Object:  Table [dbo].[People]    Script Date: 2016/3/18 17:11:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[People](
	[Age] [int] NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[PeopleId] [int] IDENTITY(1,1) NOT NULL,
	[NonIndexA] [nvarchar](255) NULL,
	[NonIndexB] [nvarchar](255) NULL,
	[IndexAPart1] [int] NULL,
	[IndexAPart2] [int] NULL,
	[IndexAPart3] [int] NULL,
	[UniquePart1] [int] NOT NULL,
	[UniquePart2] [int] NOT NULL,
 CONSTRAINT [PK_People] PRIMARY KEY CLUSTERED
(
	[PeopleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Index [IX_AGE]    Script Date: 2016/3/18 17:11:31 ******/
CREATE NONCLUSTERED INDEX [IX_AGE] ON [dbo].[People]
(
	[Age] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_INDEX_A]    Script Date: 2016/3/18 17:11:31 ******/
CREATE NONCLUSTERED INDEX [IX_INDEX_A] ON [dbo].[People]
(
	[IndexAPart1] ASC,
	[IndexAPart2] ASC,
	[IndexAPart3] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_NAME]    Script Date: 2016/3/18 17:11:31 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_NAME] ON [dbo].[People]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_UNIQ_A]    Script Date: 2016/3/18 17:11:31 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_UNIQ_A] ON [dbo].[People]
(
	[UniquePart1] ASC,
	[UniquePart2] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
