// Code generated by go-bindata.
// sources:
// tpl/mongo_collection.gogo
// tpl/mongo_foreign_key.gogo
// tpl/mongo_mongo.gogo
// tpl/mongo_orm.gogo
// tpl/mongo_search.gogo
// tpl/mssql_config.gogo
// tpl/mssql_orm.gogo
// tpl/mysql_config.gogo
// tpl/mysql_fk.gogo
// tpl/mysql_orm.gogo
// tpl/redis_config.gogo
// tpl/redis_orm.gogo
// tpl/struct.gogo
// DO NOT EDIT!

package tpl

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// tplMongo_collectionGogo reads file data from disk. It returns an error on failure.
func tplMongo_collectionGogo() (*asset, error) {
	path := "/Users/admin/aliasliyu4/src/github.com/ezbuy/ezorm/tpl/mongo_collection.gogo"
	name := "tpl/mongo_collection.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tplMongo_foreign_keyGogo reads file data from disk. It returns an error on failure.
func tplMongo_foreign_keyGogo() (*asset, error) {
	path := "/Users/admin/aliasliyu4/src/github.com/ezbuy/ezorm/tpl/mongo_foreign_key.gogo"
	name := "tpl/mongo_foreign_key.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tplMongo_mongoGogo reads file data from disk. It returns an error on failure.
func tplMongo_mongoGogo() (*asset, error) {
	path := "/Users/admin/aliasliyu4/src/github.com/ezbuy/ezorm/tpl/mongo_mongo.gogo"
	name := "tpl/mongo_mongo.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tplMongo_ormGogo reads file data from disk. It returns an error on failure.
func tplMongo_ormGogo() (*asset, error) {
	path := "/Users/admin/aliasliyu4/src/github.com/ezbuy/ezorm/tpl/mongo_orm.gogo"
	name := "tpl/mongo_orm.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tplMongo_searchGogo reads file data from disk. It returns an error on failure.
func tplMongo_searchGogo() (*asset, error) {
	path := "/Users/admin/aliasliyu4/src/github.com/ezbuy/ezorm/tpl/mongo_search.gogo"
	name := "tpl/mongo_search.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tplMssql_configGogo reads file data from disk. It returns an error on failure.
func tplMssql_configGogo() (*asset, error) {
	path := "/Users/admin/aliasliyu4/src/github.com/ezbuy/ezorm/tpl/mssql_config.gogo"
	name := "tpl/mssql_config.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tplMssql_ormGogo reads file data from disk. It returns an error on failure.
func tplMssql_ormGogo() (*asset, error) {
	path := "/Users/admin/aliasliyu4/src/github.com/ezbuy/ezorm/tpl/mssql_orm.gogo"
	name := "tpl/mssql_orm.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tplMysql_configGogo reads file data from disk. It returns an error on failure.
func tplMysql_configGogo() (*asset, error) {
	path := "/Users/admin/aliasliyu4/src/github.com/ezbuy/ezorm/tpl/mysql_config.gogo"
	name := "tpl/mysql_config.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tplMysql_fkGogo reads file data from disk. It returns an error on failure.
func tplMysql_fkGogo() (*asset, error) {
	path := "/Users/admin/aliasliyu4/src/github.com/ezbuy/ezorm/tpl/mysql_fk.gogo"
	name := "tpl/mysql_fk.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tplMysql_ormGogo reads file data from disk. It returns an error on failure.
func tplMysql_ormGogo() (*asset, error) {
	path := "/Users/admin/aliasliyu4/src/github.com/ezbuy/ezorm/tpl/mysql_orm.gogo"
	name := "tpl/mysql_orm.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tplRedis_configGogo reads file data from disk. It returns an error on failure.
func tplRedis_configGogo() (*asset, error) {
	path := "/Users/admin/aliasliyu4/src/github.com/ezbuy/ezorm/tpl/redis_config.gogo"
	name := "tpl/redis_config.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tplRedis_ormGogo reads file data from disk. It returns an error on failure.
func tplRedis_ormGogo() (*asset, error) {
	path := "/Users/admin/aliasliyu4/src/github.com/ezbuy/ezorm/tpl/redis_orm.gogo"
	name := "tpl/redis_orm.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tplStructGogo reads file data from disk. It returns an error on failure.
func tplStructGogo() (*asset, error) {
	path := "/Users/admin/aliasliyu4/src/github.com/ezbuy/ezorm/tpl/struct.gogo"
	name := "tpl/struct.gogo"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"tpl/mongo_collection.gogo":  tplMongo_collectionGogo,
	"tpl/mongo_foreign_key.gogo": tplMongo_foreign_keyGogo,
	"tpl/mongo_mongo.gogo":       tplMongo_mongoGogo,
	"tpl/mongo_orm.gogo":         tplMongo_ormGogo,
	"tpl/mongo_search.gogo":      tplMongo_searchGogo,
	"tpl/mssql_config.gogo":      tplMssql_configGogo,
	"tpl/mssql_orm.gogo":         tplMssql_ormGogo,
	"tpl/mysql_config.gogo":      tplMysql_configGogo,
	"tpl/mysql_fk.gogo":          tplMysql_fkGogo,
	"tpl/mysql_orm.gogo":         tplMysql_ormGogo,
	"tpl/redis_config.gogo":      tplRedis_configGogo,
	"tpl/redis_orm.gogo":         tplRedis_ormGogo,
	"tpl/struct.gogo":            tplStructGogo,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"tpl": &bintree{nil, map[string]*bintree{
		"mongo_collection.gogo":  &bintree{tplMongo_collectionGogo, map[string]*bintree{}},
		"mongo_foreign_key.gogo": &bintree{tplMongo_foreign_keyGogo, map[string]*bintree{}},
		"mongo_mongo.gogo":       &bintree{tplMongo_mongoGogo, map[string]*bintree{}},
		"mongo_orm.gogo":         &bintree{tplMongo_ormGogo, map[string]*bintree{}},
		"mongo_search.gogo":      &bintree{tplMongo_searchGogo, map[string]*bintree{}},
		"mssql_config.gogo":      &bintree{tplMssql_configGogo, map[string]*bintree{}},
		"mssql_orm.gogo":         &bintree{tplMssql_ormGogo, map[string]*bintree{}},
		"mysql_config.gogo":      &bintree{tplMysql_configGogo, map[string]*bintree{}},
		"mysql_fk.gogo":          &bintree{tplMysql_fkGogo, map[string]*bintree{}},
		"mysql_orm.gogo":         &bintree{tplMysql_ormGogo, map[string]*bintree{}},
		"redis_config.gogo":      &bintree{tplRedis_configGogo, map[string]*bintree{}},
		"redis_orm.gogo":         &bintree{tplRedis_ormGogo, map[string]*bintree{}},
		"struct.gogo":            &bintree{tplStructGogo, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
