name: Auto PR(v2 -> main)
on:
  push:
    branches:
      - v2
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Reset main branch
        run: |
          git fetch origin v2:v2
          git reset --hard v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: production-promotion
