name: parser

on:
  push:
    branches:
      - main
      - v2
  pull_request:
    branches:
      - main
      - v2

jobs:
  build:
    name: raw-query
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.18","1.20","1.21"]
    container:
        image: golang:${{ matrix.go }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run parser tests
        run: |
          go test -v ./internal/parser/x/query/...
